version: "3.3"

services:
  app-publish:
    working_dir: /src/go/publish/
    depends_on: 
      - redis
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/src/go/publish
      - $GOPATH/pkg/mod:/go/pkg/mod
    command: reflex -c ./app/cmd/publish/reflex.conf
    # ports:
    #   - "8080:8080"
    environment:
      - APP_ENV=development
      - APP_PORT=8080
      - REDIS_CLUSTER_ADDR=redis:6379
      - REDIS_MODE=standalone
  app-pubsub:
    working_dir: /src/go/pubSub/
    depends_on: 
      - redis
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/src/go/pubSub
      - $GOPATH/pkg/mod:/go/pkg/mod
    command: reflex -c ./app/cmd/pubSub/reflex.conf
    # ports:
    #   - "8080:8080"
    environment:
      - APP_ENV=development
      - APP_PORT=8080
      - REDIS_CLUSTER_ADDR=redis:6379
      - REDIS_MODE=standalone
  redis:
    image: redis:5.0.4
    ports:
      - 6379:6379